[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=2048' npm run build"]

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=2048' npm run build"]

[start]
cmd = "node dist/main"
